topics:
- name    : user
  topic   : cmd_vel_regulated
  timeout : 0.5
  priority: 10
- name    : move_base
  topic   : move_base/cmd_vel
  timeout : 0.5
  priority: 5


locks:
- name    : e_stop
  topic   : e_stop
  timeout : 0.0    
  priority: 255
