topics:
- name    : pad
  topic   : base_pad/cmd_vel
  timeout : 0.5
  priority: 10
- name    : follower
  topic   : follower/cmd_vel
  timeout : 0.5
  priority: 2
- name    : gui_pad
  topic   : gui_pad/cmd_vel
  timeout : 0.5
  priority: 9



locks:
- name    : e_stop
  topic   : e_stop
  timeout : 0.0    
  priority: 255
