# Publish wrench ----------------------------------
right_arm_force_torque_sensor_controller:
   type:         force_torque_sensor_controller/ForceTorqueSensorController
   publish_rate: 125

# Joint Trajectory Controller - position based -------------------------------
# For detailed explanations of parameter see http://wiki.ros.org/joint_trajectory_controller
right_arm_position_joint_trajectory_controller:
   type: position_controllers/JointTrajectoryController
   joints:
     - right_arm_shoulder_pan_joint
     - right_arm_shoulder_lift_joint
     - right_arm_elbow_joint
     - right_arm_wrist_1_joint
     - right_arm_wrist_2_joint
     - right_arm_wrist_3_joint
    ######
    # TODO: Esto no va aquí, hay que testearlo
    #joint_limits:
    #  right_arm_shoulder_pan_joint:
    #    has_position_limits: true
        # No debería dejarme poner el brazo por la derecha
    #    max_position: 1.5
    #    min_position: -1.5
        ######

   constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      right_arm_shoulder_pan_joint: {trajectory: 0.1, goal: 0.1}
      right_arm_shoulder_lift_joint: {trajectory: 0.1, goal: 0.1}
      right_arm_elbow_joint: {trajectory: 0.1, goal: 0.1}
      right_arm_wrist_1_joint: {trajectory: 0.1, goal: 0.1}
      right_arm_wrist_2_joint: {trajectory: 0.1, goal: 0.1}
      right_arm_wrist_3_joint: {trajectory: 0.1, goal: 0.1}
   stop_trajectory_duration: 0.5
   state_publish_rate:  125
   action_monitor_rate: 10

right_arm_joint_state_controller:
  type: joint_state_controller/JointStateController 
  publish_rate: 100.0
