# Settings for ros_control control loop
hardware_control_loop:
   loop_hz: 125

# Settings for ros_control hardware interface
hardware_interface:
   joints:
     - left_arm_shoulder_pan_joint
     - left_arm_shoulder_lift_joint
     - left_arm_elbow_joint
     - left_arm_wrist_1_joint
     - left_arm_wrist_2_joint
     - left_arm_wrist_3_joint

