joint_blw_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: back_left_wheel_joint

joint_brw_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: back_right_wheel_joint

joint_frw_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: front_right_wheel_joint

joint_flw_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: front_left_wheel_joint

joint_blw_position_controller:
  type: position_controllers/JointPositionController
  joint: back_left_motor_wheel_joint

joint_brw_position_controller:
  type: position_controllers/JointPositionController
  joint: back_right_motor_wheel_joint

joint_frw_position_controller:
  type: position_controllers/JointPositionController
  joint: front_right_motor_wheel_joint

joint_flw_position_controller:
  type: position_controllers/JointPositionController
  joint: front_left_motor_wheel_joint

omni_drive_controller:
  type: omni_drive_controller/OmniDriveController
  joint:
    front_right_wheel_joint:
        max_speed: 20.0 # rad/s
    front_left_wheel_joint:
        max_speed: 20.0 # rad/s
    back_right_wheel_joint:
        max_speed: 20.0 # rad/s
    back_left_wheel_joint:
        max_speed: 20.0 # rad/s
    front_right_motor_wheel_joint:
        min_angle: -2.8 # rads
        max_angle: 2.8
    front_left_motor_wheel_joint:
        min_angle: -2.8 # rads
        max_angle: 2.8
    back_right_motor_wheel_joint:
        min_angle: -2.8 # rads
        max_angle: 2.8
    back_left_motor_wheel_joint:
        min_angle: -2.8 # rads
        max_angle: 2.8
  linear_speed_limit: 3 # m/s
  linear_acceleration_limit: 3 # m/s^2
  angular_speed_limit: 3 # rad/s
  angular_acceleration_limit: 3 # rad/s^2
  odom_frame: odom
  robot_base_frame: base_footprint
  odom_broadcast_tf: true
  wheel_base: 0.934
  track_width: 0.57
  wheel_diameter: 0.186
  cmd_watchdog_duration: 0.1
  odom_publish_frequency: 100

