controller_list:
  - name: /vulcano/torso_guidance_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
        - torso_guidance_revolution_joint
        - torso_guidance_elevation_joint
  - name: /vulcano/torso_pantilt_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
        - torso_pantilt_pan_joint
        - torso_pantilt_tilt_joint
  - name: /vulcano/torso_pan_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
        - torso_pantilt_pan_joint
  - name: /vulcano/torso_tilt_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
        - torso_pantilt_tilt_joint

  - name: /vulcano/left_arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints: 
        - left_arm_shoulder_pan_joint
        - left_arm_shoulder_lift_joint
        - left_arm_elbow_joint
        - left_arm_wrist_1_joint
        - left_arm_wrist_2_joint
        - left_arm_wrist_3_joint
  - name: /vulcano/right_arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints: 
        - right_arm_shoulder_pan_joint
        - right_arm_shoulder_lift_joint
        - right_arm_elbow_joint
        - right_arm_wrist_1_joint
        - right_arm_wrist_2_joint
        - right_arm_wrist_3_joint
