controller_list:
  - name: fake_left_arm_controller
    joints:
      - left_arm_shoulder_pan_joint
      - left_arm_shoulder_lift_joint
      - left_arm_elbow_joint
      - left_arm_wrist_1_joint
      - left_arm_wrist_2_joint
      - left_arm_wrist_3_joint
  - name: fake_left_eef_controller
    joints:
      []
  - name: fake_right_arm_controller
    joints:
      - right_arm_shoulder_pan_joint
      - right_arm_shoulder_lift_joint
      - right_arm_elbow_joint
      - right_arm_wrist_1_joint
      - right_arm_wrist_2_joint
      - right_arm_wrist_3_joint
  - name: fake_right_eef_controller
    joints:
      []
  - name: fake_both_arms_controller
    joints:
      - left_arm_shoulder_pan_joint
      - left_arm_shoulder_lift_joint
      - left_arm_elbow_joint
      - left_arm_wrist_1_joint
      - left_arm_wrist_2_joint
      - left_arm_wrist_3_joint
      - right_arm_shoulder_pan_joint
      - right_arm_shoulder_lift_joint
      - right_arm_elbow_joint
      - right_arm_wrist_1_joint
      - right_arm_wrist_2_joint
      - right_arm_wrist_3_joint
  - name: fake_torso_controller
    joints:
      - torso_guidance_revolution_joint
      - torso_guidance_elevation_joint
  - name: fake_torso_eef_controller
    joints:
      - torso_guidance_elevation_joint
  - name: fake_torso_left_arm_controller
    joints:
      - torso_guidance_revolution_joint
      - torso_guidance_elevation_joint
      - left_arm_shoulder_pan_joint
      - left_arm_shoulder_lift_joint
      - left_arm_elbow_joint
      - left_arm_wrist_1_joint
      - left_arm_wrist_2_joint
      - left_arm_wrist_3_joint
  - name: fake_torso_right_arm_controller
    joints:
      - torso_guidance_revolution_joint
      - torso_guidance_elevation_joint
      - right_arm_shoulder_pan_joint
      - right_arm_shoulder_lift_joint
      - right_arm_elbow_joint
      - right_arm_wrist_1_joint
      - right_arm_wrist_2_joint
      - right_arm_wrist_3_joint
  - name: fake_torso_both_arms_controller
    joints:
      - torso_guidance_revolution_joint
      - torso_guidance_elevation_joint
      - left_arm_shoulder_pan_joint
      - left_arm_shoulder_lift_joint
      - left_arm_elbow_joint
      - left_arm_wrist_1_joint
      - left_arm_wrist_2_joint
      - left_arm_wrist_3_joint
      - right_arm_shoulder_pan_joint
      - right_arm_shoulder_lift_joint
      - right_arm_elbow_joint
      - right_arm_wrist_1_joint
      - right_arm_wrist_2_joint
      - right_arm_wrist_3_joint
  - name: fake_pantilt_controller
    joints:
      - torso_pantilt_pan_joint
      - torso_pantilt_tilt_joint
  - name: fake_pantilt_eef_controller
    joints:
      []
  - name: fake_pan_eef_controller
    joints:
      - torso_pantilt_tilt_joint
  - name: fake_pan_controller
    joints:
      - torso_pantilt_pan_joint
      - torso_pantilt_tilt_joint