controller_list:
  - name: fake_left_manipulator_controller
    joints:
      - left_arm_shoulder_pan_joint
      - left_arm_shoulder_lift_joint
      - left_arm_elbow_joint
      - left_arm_wrist_1_joint
      - left_arm_wrist_2_joint
      - left_arm_wrist_3_joint
  - name: fake_left_eef_controller
    joints:
      []
  - name: fake_right_manipulator_controller
    joints:
      - right_arm_shoulder_pan_joint
      - right_arm_shoulder_lift_joint
      - right_arm_elbow_joint
      - right_arm_wrist_1_joint
      - right_arm_wrist_2_joint
      - right_arm_wrist_3_joint
  - name: fake_right_eef_controller
    joints:
      []