pantilt_joint_state_controller:
   type:         joint_state_controller/JointStateController
   publish_rate: 50

pantilt_position_joint_trajectory_controller:
   type: position_controllers/JointTrajectoryController
   joints:
      - torso_pantilt_pan_joint
      - torso_pantilt_tilt_joint
   constraints:
      goal_time: 5.0
      torso_pantilt_pan_joint:
          trajectory: 0.60
          goal:       0.15
      torso_pantilt_tilt_joint:
          trajectory: 0.60
          goal:       0.15

tilt_position_controller:
   type: position_controllers/JointPositionController
   joint: torso_pantilt_tilt_joint

pan_position_controller:
   type: position_controllers/JointPositionController
   joint: torso_pantilt_pan_joint
